### ISSUE TITLE
Hash string does not match

### ISSUE THREAD

**Issue by benjamingb** [magiclen/passwords#4]
Hello 

I am generating the hash using the following code, but it seems that it is not a valid hash
```rust
let salt = hasher::gen_salt();
let hash_str = hasher::bcrypt_format(10, &salt, "QB3ZXBPL").unwrap();
```
This generates the following string
```
$2b$10$rH0PgZj8uowSrZ9GOft9veu4pxs8uPaVl9hXa4L3hJnblwRktfwa.
```
But when the valid in an external service (https://bcrypt-generator.com/) does not pass 

![Selection_599](https://user-images.githubusercontent.com/249177/216370703-bbdbd47f-de08-430f-b894-0b3541023f0b.png)

**Comment by benjamingb** [comment]
Is it necessary to add the character "\0" to all passwords?
why adding that if it works

**Comment by magiclen** [comment]
I think whether to add `'\0'` is up to you. With or without the null terminator, it works, though the results are different. But you should know the spec says a null terminator must be included.
