### ISSUE TITLE
Feature request: exclude set of characters

### ISSUE THREAD

**Issue by Sparkenstein** [magiclen/passwords#5]
Can you also add a feature to exclude given set of characters from the generated password? this is similar to exclude_similar except exclude given characters.

api could be something like

```rust
let pg = PasswordGenerator {
	   exclude: "aeiou",  // Exclude these characters
       length: 8,
       numbers: true,
       lowercase_letters: true,
       uppercase_letters: true,
       symbols: true,
       spaces: true,
       exclude_similar_characters: false,
       strict: true,
   };
```

resulting in generated passwords will never have aeiou regardless of other settings.

**Comment by Sparkenstein** [comment]
Also, you may want to look into optimizing performance, I compared this lib with a JavaScript lib, to generate 10k passwords with same configuration, this lib took roughly about 120ms avg. image below, and JS one took roughly 60ms.  I am pretty sure rust can easily achieve said performance, or even better one. 

![image](https://github.com/magiclen/passwords/assets/24642451/7b4e6afc-dd55-4be2-b06c-337be84f5d28)

**Comment by magiclen** [comment]
Currently, I have no plan to do this.

I wrote code to compare the performance.

Here is my Rust code

```rust
use std::time::Instant;

use passwords::PasswordGenerator;

fn main() {
    let start_time = Instant::now();

    let pg = PasswordGenerator {
        length:                     8,
        numbers:                    true,
        lowercase_letters:          true,
        uppercase_letters:          true,
        symbols:                    true,
        spaces:                     false,
        exclude_similar_characters: false,
        strict:                     true,
    };

    let result = pg.generate(10000).unwrap();

    let duration = Instant::now() - start_time;

    println!("{:?}", result);
    println!("{:?}", duration);
}
```

The `duration` is `5.40452ms`.

And here is my JS code

```typescript
import { generateMultiple } from "generate-password";

const startTime = performance.now();

const result = generateMultiple(10000, {
    length: 8,
    numbers: true,
    lowercase: true,
    uppercase: true,
    symbols: true,
    excludeSimilarCharacters: false,
    strict: true,
});

const duration = performance.now() - startTime;

console.log(result);
console.log(duration);
```

The `duration` is `22.794026` (ms).

Tested on AMD Ryzen 9 3900X @3.90Ghz.

Obviously, Rust is much faster than JS (Node.js).

**Comment by Sparkenstein** [comment]
Oh okay that's fair. will close this issue if you don't have plans for exclude implementation then. good luck 👍
